CREATE TABLE "USUARIO" (
	"USR_ID" serial NOT NULL,
	"USR_DT_HR_CAD" TIMESTAMP NOT NULL,
	"USR_USR_ID_CAD" integer NOT NULL,
	"USR_NOME" varchar(60) NOT NULL,
	"USR_SENHA" varchar(100) NOT NULL,
	"USR_SITUACAO" varchar(1) NOT NULL,
	"USR_OBSERVACAO" varchar(1000),
	"USR_FK_PFL_ID" integer,
	CONSTRAINT "PK_USR_ID" PRIMARY KEY ("USR_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "PERFIL" (
	"PFL_ID" serial NOT NULL,
	"PFL_DT_HR_CAD" TIMESTAMP NOT NULL,
	"PFL_FK_USR_ID_CAD" integer NOT NULL,
	"PFL_NOME" varchar(100) NOT NULL,
	"PFL_OBSERVACAO" varchar(1000),
	"PFL_SITUACAO" varchar(1) NOT NULL,
	CONSTRAINT "PK_PFL_ID" PRIMARY KEY ("PFL_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "ACESSO_SISTEMA" (
	"ASI_ID" serial NOT NULL,
	"ASI_DT_HR_CAD" TIMESTAMP NOT NULL,
	"ASI_FK_USR_ID_CAD" integer NOT NULL,
	"ASI_DESCRICAO" varchar(60) NOT NULL,
	CONSTRAINT "PK_ASI_ID" PRIMARY KEY ("ASI_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "PERFIL_ACESSO_SISTEMA" (
	"PAS_ID" serial NOT NULL,
	"PAS_FK_PFL_ID" integer NOT NULL UNIQUE,
	"PAS_FK_ASI_ID" integer NOT NULL UNIQUE,
	"PAS_DT_HR_CAD" TIMESTAMP NOT NULL,
	"PAS_FK_USR_ID_CAD" integer NOT NULL,
	"PAS_ACESSAR" varchar(1) NOT NULL,
	"PAS_EDITAR" varchar(1) NOT NULL,
	"PAS_EXCLUIR" varchar(1) NOT NULL,
	CONSTRAINT "PK_PAS_ID" PRIMARY KEY ("PAS_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "VINHO" (
	"VIN_ID" serial NOT NULL,
	"VIN_DT_HR_CAD" TIMESTAMP NOT NULL,
	"VIN_FK_USR_ID_CAD" integer NOT NULL,
	"VIN_NOME" varchar(100) NOT NULL,
	"VIN_CONT_GARRAFA" integer NOT NULL,
	"VIN_COMENT_SOM" varchar(255) NOT NULL,
	"VIN_TIPO_UVA" varchar(60) NOT NULL,
	"VIN_PAIS_REGIAO" varchar(60) NOT NULL,
	"VIN_CLASSIFICACAO" varchar(60) NOT NULL,
	"VIN_VINICOLA" varchar(60) NOT NULL,
	"VIN_SAFRA" integer NOT NULL,
	"VIN_AMADURECIMENTO" varchar(60) NOT NULL,
	"VIN_TEOR_ACOOLICO" varchar(60) NOT NULL,
	"VIN_TEMP_SERV" integer NOT NULL,
	"VIN_POT_GUARDA" varchar(60) NOT NULL,
	"VIN_OLFATIVO" varchar(60) NOT NULL,
	"VIN_VISUAL" varchar(60) NOT NULL,
	"VIN_GUSTATIVO" varchar(60) NOT NULL,
	CONSTRAINT "PK_VIN_ID" PRIMARY KEY ("VIN_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "ADEGA" (
	"ADG_ID" serial NOT NULL,
	"ADG_DT_HR_CAD" TIMESTAMP NOT NULL,
	"ADG_FK_USR_ID_CAD" integer NOT NULL,
	"ADG_CODIGO" integer,
	"ADG_DESCRICAO" varchar(100),
	"ADG_NRO_TOT_FILEIRA" integer NOT NULL,
	"ADG_NRO_TOT_COLUNA" integer NOT NULL,
	"ADG_NRO_TOT_POSICAO" integer NOT NULL,
	"ADG_OBSERVACAO" varchar(1000),
	"ADG_SITUACAO" varchar(1) NOT NULL,
	CONSTRAINT "PK_ADG_ID" PRIMARY KEY ("ADG_ID")
) WITH (
  OIDS=FALSE
);

CREATE TABLE "LOCAL_VINHO_ADEGA" (
	"LVA_ID" serial NOT NULL,
	"LVA_DT_HR_CAD" TIMESTAMP NOT NULL,
	"LVA_FK_USR_ID_CAD" integer NOT NULL,
	"LVA_FK_ADG_ID" integer NOT NULL UNIQUE,
	"LVA_ADG_NRO_FILEIRA" integer NOT NULL UNIQUE,
	"LVA_ADG_NRO_COLUNA" integer NOT NULL UNIQUE,
	"LVA_ADG_NRO_POSICAO" integer NOT NULL UNIQUE,
	"LVA_FK_VIN_ID" integer NOT NULL,
	CONSTRAINT "PK_LVA_ID" PRIMARY KEY ("LVA_ID")
) WITH (
  OIDS=FALSE
);

ALTER TABLE "USUARIO" ADD CONSTRAINT "FK_USR_FK_PFL_ID" FOREIGN KEY ("USR_FK_PFL_ID") REFERENCES "PERFIL"("PFL_ID");

ALTER TABLE "PERFIL" ADD CONSTRAINT "FK_PFL_FK_USR_ID_CAD" FOREIGN KEY ("PFL_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");

ALTER TABLE "ACESSO_SISTEMA" ADD CONSTRAINT "FK_ASI_FK_USR_ID_CAD" FOREIGN KEY ("ASI_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");

ALTER TABLE "PERFIL_ACESSO_SISTEMA" ADD CONSTRAINT "FK_PAS_FK_PFL_ID" FOREIGN KEY ("PAS_FK_PFL_ID") REFERENCES "PERFIL"("PFL_ID");
ALTER TABLE "PERFIL_ACESSO_SISTEMA" ADD CONSTRAINT "FK_PAS_FK_ASI_ID" FOREIGN KEY ("PAS_FK_ASI_ID") REFERENCES "ACESSO_SISTEMA"("ASI_ID");
ALTER TABLE "PERFIL_ACESSO_SISTEMA" ADD CONSTRAINT "FK_PAS_FK_USR_ID_CAD" FOREIGN KEY ("PAS_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");

ALTER TABLE "VINHO" ADD CONSTRAINT "FK_VIN_FK_USR_ID_CAD" FOREIGN KEY ("VIN_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");

ALTER TABLE "ADEGA" ADD CONSTRAINT "FK_ADG_FK_USR_ID_CAD" FOREIGN KEY ("ADG_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");

ALTER TABLE "LOCAL_VINHO_ADEGA" ADD CONSTRAINT "FK_LVA_FK_USR_ID_CAD" FOREIGN KEY ("LVA_FK_USR_ID_CAD") REFERENCES "USUARIO"("USR_ID");
ALTER TABLE "LOCAL_VINHO_ADEGA" ADD CONSTRAINT "FK_LVA_FK_ADG_ID" FOREIGN KEY ("LVA_FK_ADG_ID") REFERENCES "ADEGA"("ADG_ID");
ALTER TABLE "LOCAL_VINHO_ADEGA" ADD CONSTRAINT "FK_LVA_FK_VIN_ID" FOREIGN KEY ("LVA_FK_VIN_ID") REFERENCES "VINHO"("VIN_ID");








